
# NumPy 

NumPy (ou Numpy) é uma biblioteca de álgebra linear para Python, a razão pela qual é tão importante para a Data Science com Python é que quase todas as bibliotecas dependem do NumPy como um dos seus principais blocos de construção.

Numpy também é incrivelmente rápido, pois tem ligações para bibliotecas C. Para obter mais informações sobre por que você deseja usar Arrays em vez de listas, confira esta excelente publicação do [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Nós só aprenderemos os conceitos básicos do NumPy, para começar, precisamos instalá-lo!

## Instruções de instalação

** É altamente recomendável que instale o Python usando a distribuição da Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de Álgebra Linear) se sincronizem com o uso de uma instalação conda. Se você tiver o Anaconda, instale o NumPy acessando seu terminal ou prompt de comando e digite: **

    conda install numpy
    
** Se você não possui Anaconda e não pode instalá-lo, consulte: [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [1]:
import numpy as np

Numpy possui muitas funções e capacidades incorporadas. Não vamos cobri-los na totalidade, mas, em vez disso, vamos nos concentrar em alguns dos aspectos mais importantes de Numpy: vetores, arrays, matrizes e geração de números. Comecemos por arrays:

# Numpy Arrays

As matrizes de NumPy são a maneira principal de usar Numpy ao longo do curso. Numpy arrays essencialmente vêm de duas formas: vetores e matrizes. Os vetores são estritamente arranjos de 1d e as matrizes são 2d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes numPy.


## Criando NumPy Arrays

### De uma lista de Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [1]:
import numpy as np

In [3]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [10]:
np.array(minha_lista)

array([1, 2, 3])

In [2]:
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
#matriz 3x3
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados (Built-in Methods)

Há muitas maneiras embutidas de gerar Arrays

### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,11,3)

array([0, 3, 6, 9])

### zeros e ones

Gerar matrizes de zeros ou de ums

In [21]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [20]:
type(a)

numpy.ndarray

In [12]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
np.ones(3)

array([ 1.,  1.,  1.])

In [5]:
np.ones((3,3)) *3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [26]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

## eye

Cria uma matriz identidade

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy também tem muitas maneiras de criar arrays de números aleatórios:

### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``. 
Nao precisa de tupla para matriz

In [29]:
np.random.rand(3) 

array([0.2002628 , 0.78306518, 0.2529016 ])

In [21]:
np.random.rand(5,5)

array([[ 0.17673782,  0.89778905,  0.63435534,  0.71063947,  0.77599807],
       [ 0.43508517,  0.91318032,  0.26845102,  0.47684911,  0.99352832],
       [ 0.46549283,  0.61358868,  0.83033769,  0.96269353,  0.40539354],
       [ 0.42690345,  0.62643046,  0.63229206,  0.70472064,  0.56361411],
       [ 0.64975573,  0.99581894,  0.22271032,  0.98653378,  0.81032733]])

### randn

Retorna uma amostra (ou amostras) da distribuição "normal". Ao contrário de rand, que é uniforme:

In [22]:
np.random.randn(2)

array([ 0.0767673 ,  1.62725754])

In [23]:
np.random.randn(5,5)

array([[-0.87657556,  0.03151182,  0.83685254,  0.47021414,  0.05169247],
       [ 0.12624043, -1.67384753, -0.26116216,  0.54199188,  1.35609602],
       [-1.89332603, -0.53626069,  1.97356854, -0.42423178, -1.44121779],
       [-0.87702313, -1.2751979 ,  0.66739175,  1.6723646 ,  0.26337179],
       [-0.050468  , -0.13342553,  0.16537819,  0.02001319,  0.14597014]])

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (exclusivo).

In [8]:
np.random.randint(1,100)

9

In [9]:
np.random.randint(1,100,10)

array([58, 47, 76, 71, 30, 95, 30, 13, 85,  6])

## Atributos de Array e Métodos

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [39]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr

array([ 6, 18, 48,  0,  9, 48, 37, 49,  4, 43])

## Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [12]:
arr = np.arange(30)

In [14]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar ``seus locais`` de índice usando argmin ou argmax

In [17]:
ranarr=np.random.randint(1,100,5)
ranarr

array([61, 99, 37, 53, 81])

In [18]:
ranarr.max()

99

In [19]:
#indice do maximo
ranarr.argmax()

1

In [20]:

ranarr.min()

37

In [21]:
#indice do minimo
ranarr.argmin()

2

## Shape

Shape é um atributo que os arrays têm (não um método):

In [22]:
# Vector
arr.shape

(30,)

In [23]:
arr.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [24]:
arr.reshape(1,30).shape

(1, 30)

In [25]:
arr.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Você também pode pegar o tipo de dados do objeto na matriz:

In [27]:
ranarr.dtype

dtype('int32')