![imagem%20unesp%20rosana.jpg](attachment:imagem%20unesp%20rosana.jpg)
# Indexação de Numpys e Arrays

Nesta palestra, vamos discutir como selecionar elementos ou grupos de elementos de uma matriz.

In [1]:
import numpy as np

In [2]:
# Criando um simples array
arr = np.arange(0,11)

In [3]:
# Mostrar
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexação e seleção
A maneira mais simples de escolher um ou alguns elementos de uma matriz é muito semelhante às listas de python:

In [4]:
# Obtendo um valor através de um índice
arr[8]

8

In [5]:
# Obtendo valores em um intervalo
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Transmissão

Numpy arrays diferem de uma lista Python normal por causa de sua capacidade de transmissão:

In [7]:
# Configurando um valor com intervalo de índice (Transmissão)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Redefinir matriz, veremos por que eu tive que redefinir em um momento
arr = np.arange(0,11)

# Mostrando
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# Notas importantes sobre fatias
slice_de_arr = arr[0:6].copy

# Mostra a fatia
slice_de_arr

<function ndarray.copy>

In [7]:
# Modifica a fatia
slice_de_arr[:]=50

#Show Slice again
slice_de_arr

TypeError: 'builtin_function_or_method' object does not support item assignment

Agora note que as mudanças também ocorrem em nossa matriz original!

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Os dados não são copiados, é uma visão da matriz original! Isso evita problemas de memória!

In [12]:
# Para obter uma cópia, precisa ser explícito
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexando uma matriz 2D

O formato geral é ** arr_2d [row] [col] ** ou ** arr_2d [row, col] **. Eu recomendo geralmente usando a notação de vírgula para maior clareza.

In [8]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

# Mostrando
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
# Fila de indexação
arr_2d[0]


array([ 5, 10, 15])

In [11]:
# O formato é arr_2d [row] [col] ou arr_2d [row, col]

# Obtendo o valor do elemento individual
arr_2d[1][0]

20

In [25]:
# Obtendo o valor do elemento individual
arr_2d[1,0]

20

In [12]:
# Fatiando um array 2D

# Fatia (2,2) do canto superior direito
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
# Fatia inferior
arr_2d[2]

array([35, 40, 45])

In [28]:
# Fatia inferior
arr_2d[2,:]

array([35, 40, 45])

### Indexação "Fancy"

A indxação "Fancy" permite que você selecione linhas inteiras ou colunas fora de ordem, para mostrar isso, vamos construir rapidamente uma matriz numpy:

In [13]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
# Tamaho do array
arr_length = arr2d.shape[1]
arr_length

10

In [21]:
for i in range(arr_length):
    arr2d[:,i] = i
    
arr2d

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

Indexação "Fancy" permite o seguinte:

In [22]:
arr2d[:,[2,4,6,8]]

array([[2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.]])

In [23]:
# Permite em qualquer ordem
arr2d[[6,4,2,7]]

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

## Seleção

Vamos examinar brevemente como usar colchetes para seleção com base em operadores de comparação.

In [26]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [28]:
bool_arr = arr>4

In [29]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [30]:
arr[bool_arr=!True]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])