In [ ]:
#Matrizes são objetos ESTRITAMENTE bidimensionais, o que torna mais fácil as operações aritméticas

In [1]:
import numpy as np

In [2]:
A = np.matrix([[1, 2], [3, 4]])

B = np.matrix([[5, 3], [8, 7]])

Z = np.array([
    [[2,6], [8,4]] , 
    [[2,6], [8,4]],
    [[2,6], [8,4]]
])

Y = np.array([2,6,8,4])

In [3]:
A

matrix([[1, 2],
        [3, 4]])

In [3]:
Z = np.matrix([
    [[2,6], [8,4]] , 
    [[2,6], [8,4]],
    [[2,6], [8,4]]
])

ValueError: matrix must be 2-dimensional

In [4]:
print(type(A))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [5]:
print(type(Z))

<class 'numpy.ndarray'>


In [6]:
print(type(Y))

<class 'numpy.ndarray'>


In [7]:
print(A)

[[1 2]
 [3 4]]


In [8]:
print(Z)

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [9]:
print(Y)

[2 6 8 4]


In [10]:
Z.shape

(3, 2, 2)

In [11]:
Y.shape

(4,)

## Soma

In [12]:
print(A + B)

[[ 6  5]
 [11 11]]


In [13]:
print(B + 3)

[[ 8  6]
 [11 10]]


## Subtração

In [14]:
print(A-B)

[[-4 -1]
 [-5 -3]]


## Multiplicação

In [15]:
A = np.matrix([[1, 2], [3, 4]])

print(A)

[[1 2]
 [3 4]]


In [16]:
#Arrumação em "cruz"

print (A * A)

[[ 7 10]
 [15 22]]


In [17]:
#Multiplicação Indice a Indice

print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


## Inversa

In [18]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
from numpy.linalg import inv

In [1]:
from numpy.random import rand

In [3]:
r = rand()
a.r(10)

NameError: name 'a' is not defined

In [20]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


## Transposta

In [21]:
print(A.T)

[[1 3]
 [2 4]]
