# Transposição e Reshaping de Arrays

In [60]:
import numpy as np

In [3]:
A = np.array([[10, 20, 30], [40, 50, 60]])

In [4]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [6]:
np.transpose(A)

array([[10, 40],
       [20, 50],
       [30, 60]])

## Broadcasting

In [7]:
B = np.array([[100, 200, 300]])

In [8]:
B.T

array([[100],
       [200],
       [300]])

In [9]:
B.T + B

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

## Convertendo Matrizes em Arrays

In [2]:
A = np.array([np.arange(10,60,10), np.arange(100,150,10)])

In [3]:
A

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [4]:
A.shape

(2, 5)

In [5]:
A.ravel()

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [7]:
A

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [6]:
A.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

## Operadores Lógicos

In [12]:
array = np.random.randint(1, 10, size = (4,4))

In [13]:
array

array([[6, 3, 4, 8],
       [1, 2, 4, 5],
       [6, 8, 8, 7],
       [6, 7, 6, 6]])

In [14]:
np.any((array % 7) == 0)

True

In [19]:
np.all(array < 5)

False

## Reshaping

In [16]:
array = np.arange(1,16)

In [17]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
array.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Ordenando o Array

In [57]:
array = np.random.randint(1, 10, size = (4,4))
array

array([[4, 3, 8, 1],
       [3, 8, 4, 2],
       [8, 4, 4, 1],
       [5, 8, 7, 5]])

In [58]:
array.sort(axis=0)

In [59]:
array

array([[3, 3, 4, 1],
       [4, 4, 4, 1],
       [5, 8, 7, 2],
       [8, 8, 8, 5]])

In [39]:
# Ordenando por linhas
b.sort(axis = 1)

In [41]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
array = np.array([[3,2],[10,-1]])

In [ ]:
array

In [ ]:
# Ordenando por colunas
array.sort(axis = 0,kind='heapsort')

In [ ]:
array